In [1]:
import pandas as pd

## practice

In [2]:
df = pd.read_csv('data\placement.csv')
df

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Syed\AppData\Local\Temp\ipykernel_10868\2812199135.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('data\placement.csv')

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

## practice

In [3]:
df.iloc[0:5,0:3]

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [5]:
df.loc[10:20,['cgpa']]

    cgpa
10  6.18
11  5.44
12  6.09
13  8.50
14  7.51
15  8.88
16  8.04
17  7.81
18  5.94
19  6.75
20  5.80

## practice

In [6]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

## practice

In [8]:
x=df.drop(columns=['placed'])
y=df['placed']
x.head()

   cgpa  resume_score
0  8.14          6.52
1  6.17          5.17
2  8.27          8.86
3  6.88          7.27
4  7.52          7.30

## practice

In [9]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: placed, dtype: int64

## practice

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cgpa          100 non-null    float64
 1   resume_score  100 non-null    float64
 2   placed        100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

## .values

In [12]:
## It give the array of the numerical data
df.values

array([[8.14, 6.52, 1.  ],
       [6.17, 5.17, 0.  ],
       [8.27, 8.86, 1.  ],
       [6.88, 7.27, 1.  ],
       [7.52, 7.3 , 1.  ],
       [8.77, 6.19, 1.  ],
       [5.34, 7.09, 0.  ],
       [6.56, 6.29, 0.  ],
       [6.32, 6.71, 0.  ],
       [7.69, 7.12, 1.  ],
       [6.18, 6.35, 0.  ],
       [5.44, 6.54, 0.  ],
       [6.09, 7.01, 0.  ],
       [8.5 , 5.09, 1.  ],
       [7.51, 6.25, 1.  ],
       [8.88, 5.93, 1.  ],
       [8.04, 7.64, 1.  ],
       [7.81, 8.71, 1.  ],
       [5.94, 5.88, 0.  ],
       [6.75, 8.11, 1.  ],
       [5.8 , 8.06, 0.  ],
       [6.53, 7.64, 0.  ],
       [6.16, 5.77, 0.  ],
       [6.05, 7.13, 0.  ],
       [8.22, 6.18, 1.  ],
       [7.76, 5.68, 1.  ],
       [6.27, 6.47, 0.  ],
       [5.51, 6.15, 0.  ],
       [7.46, 7.67, 1.  ],
       [6.19, 7.3 , 0.  ],
       [7.36, 7.15, 1.  ],
       [5.92, 7.02, 0.  ],
       [5.87, 7.96, 0.  ],
       [8.43, 7.73, 1.  ],
       [8.87, 7.19, 1.  ],
       [8.07, 7.48, 1.  ],
       [8.16, 7.56, 1.  ],
       [9.05, 8.21, 1.  ],
       [6.  , 8.72, 0.  ],
       [7.5 , 6.19, 1.  ],
       [8.25, 5.32, 1.  ],
       [8.68, 5.15, 1.  ],
       [6.9 , 6.91, 1.  ],
       [8.21, 7.95, 1.  ],
       [5.47, 5.92, 0.  ],
       [8.1 , 5.44, 1.  ],
       [5.83, 5.21, 0.  ],
       [7.05, 8.14, 1.  ],
       [5.54, 6.57, 0.  ],
       [5.46, 6.73, 0.  ],
       [8.22, 6.74, 1.  ],
       [6.54, 7.39, 0.  ],
       [5.9 , 7.5 , 0.  ],
       [6.  , 7.16, 0.  ],
       [5.92, 7.18, 0.  ],
       [6.94, 6.87, 1.  ],
       [6.13, 6.43, 0.  ],
       [6.34, 7.21, 0.  ],
       [6.47, 7.37, 0.  ],
       [5.95, 7.57, 0.  ],
       [5.87, 6.64, 0.  ],
       [6.89, 7.96, 1.  ],
       [5.75, 8.43, 0.  ],
       [8.65, 7.58, 1.  ],
       [7.93, 8.09, 1.  ],
       [6.04, 8.75, 0.  ],
       [8.35, 8.02, 1.  ],
       [6.59, 6.81, 1.  ],
       [6.01, 7.49, 0.  ],
       [8.06, 9.06, 1.  ],
       [7.12, 7.41, 1.  ],
       [7.34, 8.22, 1.  ],
       [7.63, 7.98, 1.  ],
       [5.76, 6.48, 0.  ],
       [5.54, 7.36, 0.  ],
       [6.34, 7.94, 1.  ],
       [9.4 , 5.5 , 1.  ],
       [5.88, 6.92, 0.  ],
       [5.79, 5.66, 0.  ],
       [5.27, 7.28, 0.  ],
       [7.83, 7.7 , 1.  ],
       [6.12, 6.72, 0.  ],
       [7.92, 6.06, 1.  ],
       [7.6 , 8.08, 1.  ],
       [5.76, 6.49, 0.  ],
       [6.72, 5.46, 0.  ],
       [6.18, 5.76, 0.  ],
       [5.62, 5.05, 0.  ],
       [8.07, 6.07, 1.  ],
       [5.99, 7.49, 0.  ],
       [5.85, 5.56, 0.  ],
       [8.28, 6.3 , 1.  ],
       [5.43, 6.18, 0.  ],
       [9.31, 7.39, 1.  ],
       [8.01, 4.95, 1.  ],
       [6.33, 6.38, 0.  ],
       [8.23, 7.76, 1.  ],
       [6.65, 7.78, 0.  ],
       [8.14, 5.63, 1.  ],
       [6.09, 6.61, 0.  ]])

## sort

In [ ]:
## To sort the data
p = df.sort_values(by= "resume_score", ascending=False)
p
s = df.sort_values(by='cgpa',ascending=True)
s

# sort is used to sort the data according to your need

    cgpa  resume_score  placed
79  5.27          7.28       0
6   5.34          7.09       0
92  5.43          6.18       0
11  5.44          6.54       0
49  5.46          6.73       0
..   ...           ...     ...
34  8.87          7.19       1
15  8.88          5.93       1
37  9.05          8.21       1
93  9.31          7.39       1
76  9.40          5.50       1

[100 rows x 3 columns]

## type-casting (astype())

In [46]:
## Type-cating function (astype())
df['cgpa'] = df['cgpa'].astype(str)
df.dtypes

df['placed'] = df['placed'].astype(str)
df.dtypes

df['placed'] = df['placed'].astype(int)
df.dtypes

cgpa                str
resume_score    float64
placed            int64
dtype: object

In [22]:
df['cgpa'] = df['cgpa'].astype(float)

In [24]:
df = pd.read_csv('data\placement.csv')

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Syed\AppData\Local\Temp\ipykernel_10868\1730237107.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('data\placement.csv')

## add and sub

In [ ]:
## Add and Sub
df['resume_score_add'] = df['resume_score'].add(5)
df["cgpa"] = df["cgpa"].astype(float)
df['cgpa_sub'] = df['cgpa'].sub(2)
df.head()

df['resume_score_org'] = df['resume_score'].sub(5)
df['cgpa_org'] = df['cgpa'].add(2)
df.head()

# it is used to perform arithmetic operation in dataset

,cgpa,resume_score,placed,resume_score_add,resume_score_org,cgpa_sub,cgpa_org
0,8.14,6.52,1,11.52,1.52,6.14,10.14
1,6.17,5.17,0,10.17,0.17,4.17,8.17
2,8.27,8.86,1,13.86,3.86,6.27,10.27
3,6.88,7.27,1,12.27,2.27,4.88,8.88
4,7.52,7.30,1,12.30,2.30,5.52,9.52

In [ ]:
df[['cgpa', 'placed']]

df[['cgpa','resume_score']]

# it is use to filter the data according to our need

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

## .filter

In [ ]:
## 0 --> Rows, 1 ---> Columns
## Filter based on rows-wise operations
df.filter(items= [10,11], axis=0)

df.filter(items=[5,15], axis=0)

df.filter(items=['cgpa','placed'],axis=1)

# it is used to give you the filtered items 
# if you want it in rows you have to mention index no. in items
# if you want it in the column you have to mention name of the columns

    cgpa  placed
0   8.14       1
1   6.17       0
2   8.27       1
3   6.88       1
4   7.52       1
..   ...     ...
95  6.33       0
96  8.23       1
97  6.65       0
98  8.14       1
99  6.09       0

[100 rows x 2 columns]

## filter based on likeness

In [ ]:
## Filter based on likeness
df.filter(like ='6', axis=0)

df.filter(like= '3',axis=0)

# it is used to give you the no. which is present in the index

,cgpa,resume_score,placed,resume_score_add,resume_score_org,cgpa_sub,cgpa_org
3,6.88,7.27,1,12.27,2.27,4.88,8.88
13,8.50,5.09,1,10.09,0.09,6.50,10.50
23,6.05,7.13,0,12.13,2.13,4.05,8.05
30,7.36,7.15,1,12.15,2.15,5.36,9.36
31,5.92,7.02,0,12.02,2.02,3.92,7.92
32,5.87,7.96,0,12.96,2.96,3.87,7.87
33,8.43,7.73,1,12.73,2.73,6.43,10.43
34,8.87,7.19,1,12.19,2.19,6.87,10.87
35,8.07,7.48,1,12.48,2.48,6.07,10.07
36,8.16,7.56,1,12.56,2.56,6.16,10.16
37,9.05,8.21,1,13.21,3.21,7.05,11.05
38,6.00,8.72,0,13.72,3.72,4.00,8.00
39,7.50,6.19,1,11.19,1.19,5.50,9.50
43,8.21,7.95,1,12.95,2.95,6.21,10.21
53,6.00,7.16,0,12.16,2.16,4.00,8.00
63,8.65,7.58,1,12.58,2.58,6.65,10.65
73,5.76,6.48,0,11.48,1.48,3.76,7.76
83,7.60,8.08,1,13.08,3.08,5.60,9.60
93,9.31,7.39,1,12.39,2.39,7.31,11.31

## .where

In [ ]:
df = pd.read_csv('data\placement.csv')

## To where the data based on condition
df['cgpa'].where(df['cgpa'] > 7, other="Fail")

df['placed'].where(df['placed']>=1, other='zero')

# where is used to write conditions

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Syed\AppData\Local\Temp\ipykernel_10868\6769575.py:1: SyntaxWarning: invalid escape sequence '\p'
  df = pd.read_csv('data\placement.csv')

0        1
1     zero
2        1
3        1
4        1
      ...
95    zero
96       1
97    zero
98       1
99    zero
Name: placed, Length: 100, dtype: object